### ISSUE TITLE
Pico 4 Support

### ISSUE THREAD

**Issue by CatBallV** [QuestCraftPlusPlus/QCXR-XR-Wrapper#12]
[latestlog1535.txt](https://github.com/QuestCraftPlusPlus/QCXR-XR-Wrapper/files/13797433/latestlog1535.txt)
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Adreno (TM) 650) doesn't support base Zink requirements: feats.features.logicOp

**Comment by CatBallV** [comment]
I really want it to run on Pico.

**Comment by Cartrigger** [comment]
you cannot run it on pico by slightly changing things, we will have to manually support it. 
the renderer doesn't support it without changes.

**Comment by CatBallV** [comment]
> you cannot run it on pico by slightly changing things, we will have to manually support it. the renderer doesn't support it without changes. (due to said changes to Quest)

Okay, thank you for your reply

**Comment by thejudge156** [comment]
Reopening, as we do want to support this. Unsure why CADIndie closed it.
