### ISSUE TITLE
Building And Starting

### ISSUE THREAD

**Issue by Gabriel-githud** [QuestCraftPlusPlus/QCXR-XR-Wrapper#37]
When I Build A Test QCXR Apk From This Repository It Builds Successfully And When I Go Test It Out On My Headset It Tries To Open Then Immediately Crashes
Any Fixes?

**Comment by Killerminigun** [comment]
Selfmade builds dont receive support.

**Comment by itsnotalexthere** [comment]
Should not be an issue, when using self-made builds, don't expect everything to work out of the box

**Comment by Cartrigger** [comment]
Self made builds are not supported at all and any bug reports are invalid.

**Comment by computer-catt** [comment]
you might have some luck opening logcat and seeing what error you get
i wouldn't *really* bother though
